### ISSUE TITLE
💡 New Rule: prefer concatLatestFrom

### ISSUE THREAD

**Issue by minijus** [timdeschryver/eslint-plugin-ngrx#100]
With version 11 NgRx has `concatLatestFrom` lazy operator which should be used instead of eager operators `withLatestFrom`. This would be applicable for effects and if possible for components/services.

Documentation on `concatLatestFrom`: https://ngrx.io/guide/effects/operators#concatlatestfrom

**Comment by timdeschryver** [comment]
That's a good idea @minijus 
If you want, feel free to open a PR..
