### ISSUE TITLE
An unhandled exception occurred: Error while loading rule 'ngrx/avoid-combining-selectors': Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by nolafs** [timdeschryver/eslint-plugin-ngrx#101]
Getting the following error

An unhandled exception occurred: Error while loading rule 'ngrx/avoid-combining-selectors': Cannot read property 'find' of undefined

**Comment by timdeschryver** [comment]
Hi thanks for opening this issue @nolafs . By any chance, do you know which code causes this exception?

**Comment by timdeschryver** [comment]
I was unable to reproduce this, so I tried a to fix the bug...
Could try against v1.17.4 please?

**Comment by nolafs** [comment]
Test it, the previous error seems to be resolved but I am getting new one now.

An unhandled exception occurred: Error while loading rule 'rxjs/no-cyclic-action': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser

`{
  "root": true,
  "ignorePatterns": [
   
  ],
  "overrides": [
    {
      "files": [
        "*.ts"
      ],
      "parser": "@typescript-eslint/parser",
      "parserOptions": {
        "ecmaVersion": 2019,
        "project": "./tsconfig.json",
        "sourceType": "module"
      },
      "extends": [
        "plugin:@angular-eslint/ng-cli-compat",
        "plugin:@angular-eslint/ng-cli-compat--formatting-add-on",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "plugins": [
        "eslint-plugin-react",
        "ngrx"
      ],
      "rules": {
        "ngrx/select-style": "error",
        "arrow-parens": [
          "off",
          "always"
        ],
        "brace-style": [
          "off",
          "off"
        ],
        "@typescript-eslint/naming-convention": [
          "error",
          {
            "selector": "enumMember",
            "format": [
              "UPPER_CASE"
            ]
          }
        ],
        "ngrx/avoid-combining-selectors": "off",
        "linebreak-style": "off",
        "new-parens": "off",
        "newline-per-chained-call": "off",
        "no-extra-semi": "off",
        "no-irregular-whitespace": "off",
        "no-trailing-spaces": "off",
        "no-underscore-dangle": "off",
        "react/jsx-curly-spacing": "off",
        "react/jsx-equals-spacing": "off",
        "react/jsx-wrap-multilines": "off",
        "space-in-parens": [
          "off",
          "never"
        ]
      }
    },

    {
      "files": [
        "*.html"
      ],

      "extends": [
        "plugin:@angular-eslint/template/recommended",
        "plugin:ngrx/recommended"
      ],
      "rules": {}
    }
  ]
}
`

**Comment by nolafs** [comment]
Thanks, it working now.

**Comment by timdeschryver** [comment]
Thanks for the update @nolafs 👍
