### ISSUE TITLE
Update doc for prefer-concat-latest-from

### ISSUE THREAD

**Issue by david-shortman** [timdeschryver/eslint-plugin-ngrx#127]
It should be
`concatLatestFrom(() => this.store.select(selectProducts)),`

_Originally posted by @minijus in https://github.com/timdeschryver/eslint-plugin-ngrx/pull/122#r625016619_

**Comment by timdeschryver** [comment]
😅 thanks, I totally overlooked that, and also the comment on the PR.
Feel free to open a Pull Request.

**Comment by david-shortman** [comment]
lol no prob got one open
