### ISSUE TITLE
Rules migration status

### ISSUE THREAD

**Issue by jsaguet** [timdeschryver/eslint-plugin-ngrx#15]
I wanted to create this issue to follow-up the rules migration from ngrx-tslint-rules.
This could also be useful integrated as documentation for new users or if we want to implement a migration schematic in the end (in this repo or in [@angular-eslint](https://github.com/angular-eslint/angular-eslint))

The following table gives the tslint rule name, the corresponding eslint rule name and the status

| TSLint Rule| ESLint Rule| Status                                                                                                                                             |
| ---------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------- |
| ngrx-action-hygiene                                  | ngrx/action-hygiene                                                                                        | :heavy_check_mark: Done                                  |
| ngrx-avoid-dispatching-multiple-actions-sequentially | ngrx/avoid-dispatching-multiple-actions-sequentially                                                                        | :heavy_check_mark: Done |
| ngrx-effect-creator-and-decorator                    | ngrx/no-effect-decorator-and-creator | :heavy_check_mark: Done                    |
| ngrx-no-dispatch-in-effects                          | ngrx/no-dispatch-in-effects                                                        | :heavy_check_mark: Done                         |
| ngrx-no-duplicate-action-types                       |  -                       | Managed by `strictActionTypeUniqueness` runtime check in NGRX >= 9.2.0<br>See https://github.com/ngrx/platform/pull/2520
| ngrx-no-effect-decorator                             | ngrx/no-effect-decorator                                                                                 | :heavy_check_mark: Done                            |
| ngrx-no-effects-in-providers                         | ngrx/no-effects-in-providers                                              | :heavy_check_mark: Done                         |
| ngrx-no-multiple-actions-in-effects                  | ngrx/no-multiple-actions-in-effects                                                                                   | :heavy_check_mark: Done                 |
| ngrx-no-multiple-stores                              | ngrx/no-multiple-stores                                                                                      | :heavy_check_mark: Done                              |
| ngrx-no-reducer-in-key-names                         | ngrx/no-reducer-in-key-names                                                                                      |  :heavy_check_mark: Done                               |
| ngrx-no-typed-store                                  | ngrx/no-typed-store                                                                                                    | :heavy_check_mark: Done                                  |
| ngrx-selector-for-select                             | ngrx/use-selector-in-select                                                        | :heavy_check_mark: Done                             |
| ngrx-on-reducer-explicit-return-type           | ngrx/on-function-explicit-return-type                                                        | :heavy_check_mark: Done                       |

**Comment by timdeschryver** [comment]
Awesome, `ngrx-no-duplicate-action-types` is indeed not needed.
It would also be hard to do with eslint I think, as it looks across files.

**Comment by jsaguet** [comment]
> 
> 
> Awesome, `ngrx-no-duplicate-action-types` is indeed not needed.
> It would also be hard to do with eslint I think, as it looks across files.
👍 
> 
> `no-duplicate-action-in-reducer` should be removed - this is now supported in NgRx.
How do you enable this? I think I never saw it

**Comment by timdeschryver** [comment]
Do you got some code to share, and what's the NgRx version you're on?

**Comment by jsaguet** [comment]
I created a repository https://github.com/jsaguet/ngrx-duplicate-action-repro
I don't see any error from ngrx of duplicate actions either when using directly the action in the reducer or actions in an object.
Do I need to enable something to see it? Is it reported at build type or directly in the editor?

**Comment by timdeschryver** [comment]
That's now become valid in NgRx.
It will invoke all reducer actions, if you add the same action twice, both will be invoked.

**Comment by jsaguet** [comment]
OK so the rule should be removed because it is valid ? I understood that it should be removed because the error was displayed by ngrx

**Comment by timdeschryver** [comment]
Exactly @jsaguet it's now valid.

**Comment by timdeschryver** [comment]
We can add #36 to the list when it gets merged :)

**Comment by jsaguet** [comment]
Rule was added to the list

**Comment by timdeschryver** [comment]
@all-contributors please add @jsaguet for ideas

**Comment by timdeschryver** [comment]
@all-contributors please add @StephenCooper for ideas

**Comment by timdeschryver** [comment]
Thansk for your work on this @jsaguet , what do you think about becoming a collaborator 😁?

**Comment by jsaguet** [comment]
I'd be glad to continue helping you out on this project however I can! 🙂

**Comment by timdeschryver** [comment]
Putting a fix for `ngrx/on-function-explicit-return-type` in the tslint package here, so we won't forget about it.

https://github.com/timdeschryver/ngrx-tslint-rules/pull/37

**Comment by timdeschryver** [comment]
I think this issue can be closed 🎉

**Comment by jsaguet** [comment]
Yes, I guess now it's time to write a bit of documentation 😄

**Comment by timdeschryver** [comment]
Awesome, thanks again @jsaguet !
