### ISSUE TITLE
Readme: 404 for link to docs on ngrx/avoid-duplicate-actions-in-reducer 

### ISSUE THREAD

**Issue by robinpellegrims** [timdeschryver/eslint-plugin-ngrx#154]
The link in the README file for the `ngrx/avoid-duplicate-actions-in-reducer` rule is referencing a page that does not exist.

Currently it is referencing 
```
https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/avoid-duplicate-actions-in-reducer
```

while I suppose it should be referencing

```
https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/docs/rules/avoid-duplicate-actions-in-reducer.md
```

Let me know if you want me to create a PR (though the fix is fairly simple :-))

**Comment by timdeschryver** [comment]
Thanks for opening this issue @robinpellegrims .
I kind of went straight ahead and "implemented" the fix, sorry 🙈.
