### ISSUE TITLE
Missing "positive" or "correct" examples in some of the examples

### ISSUE THREAD

**Issue by MaximeKoitsalu** [timdeschryver/eslint-plugin-ngrx#16]
Hi,

I greatly appreciate tools like yours but was wondering if there are any plans to add examples on how to correctly handle the different errors and warnings your linter provides.

For example, with the rule `ngrx-avoid-dispatching-multiple-actions-sequentially`. What is the correct way of doing this?

Thanks

**Comment by timdeschryver** [comment]
Transfered this issue over to ESLint, as this is the future and providing docs is included within ESLint.

**Comment by timdeschryver** [comment]
All rules are documented and can be found [here](https://github.com/timdeschryver/eslint-plugin-ngrx/tree/master/docs/rules) 🎉
