### ISSUE TITLE
Setup an internal package for repo maintenance

### ISSUE THREAD

**Issue by rafaelss95** [timdeschryver/eslint-plugin-ngrx#206]
To track the plans about the linter for repo maintenance discussed a bit at https://github.com/timdeschryver/eslint-plugin-ngrx/pull/185#issuecomment-913007070.

**Comment by timdeschryver** [comment]
Feel free to take this one @rafaelss95

**Comment by rafaelss95** [comment]
Do you have something in mind? Like.. where should I start?
