### ISSUE TITLE
Add documentation about suggestions on README 

### ISSUE THREAD

**Issue by rafaelss95** [timdeschryver/eslint-plugin-ngrx#207]
## Information
Documentation about suggestions on README.

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Do you want to work on this, or can I? 😁
It might take a week before I can pick this one up though.

**Comment by timdeschryver** [comment]
Oh, I misread the issue; I was thinking about also adding this information to the docs of the rules doc.

**Comment by rafaelss95** [comment]
Hmm, do you think it's still necessary to document this in each rule?
