### ISSUE TITLE
Bug configuration failed

### ISSUE THREAD

**Issue by bryantlikes** [timdeschryver/eslint-plugin-ngrx#272]
## Behavior

    Something went wrong while adding the NgRx ESLint Plugin.
    The NgRx ESLint Plugin is installed but not configured.

    Please see https://github.com/timdeschryver/eslint-plugin-ngrx/#eslint-plugin-ngrx to configure the NgRx ESLint Plugin.

    Details:
    Unexpected token / in JSON at position 1165

Maybe the issue is because I'm using .eslintrc.json instead of .js? Just thought I would pass this along. 

## Code snippet

Already had eslint installed, just using ng add to install eslint-plugin-ngrx

## I would be willing to submit a PR to fix this issue :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[X] No (not familiar with this code)

**Comment by timdeschryver** [comment]
Hi, sorry to hear that.
My guess is that there are some comments included in the eslint config file.
Could you please verify that? Thanks!

**Comment by bryantlikes** [comment]
Yes, you are correct, there are comments in the file.

**Comment by timdeschryver** [comment]
👍 thanks for the update @bryantlikes
