### ISSUE TITLE
💡 entityAdapter.getSelectors() should be invoked without params

### ISSUE THREAD

**Issue by timdeschryver** [timdeschryver/eslint-plugin-ngrx#279]
https://github.com/ngrx/platform/issues/3270#issuecomment-1014797966

This would also be the first `entity` rule, so we need some extra config to create a specific `entity` config.

**Comment by PixelatedFigure** [comment]
The only parameter for the getSelector method is a state selector that gets the slice needed for the adapter to properly function, invoking it without parameters assumes the state of the adapter is the root state of the application which is usually not the case.
