### ISSUE TITLE
prefer-concat-latest-from not working for multiple arguments

### ISSUE THREAD

**Issue by danielnemetz** [timdeschryver/eslint-plugin-ngrx#280]
## prefer-concat-latest-from should detect `withLatestFrom` with multiple arguments

If `withLatestFrom` is used with more than one observable it should be detected with the given rule. Instead it is ignored and just works for withLatestFrom with one argument at most.

## Works

`withLatestFrom(observable$)`

## Doesn't work

`withLatestFrom(observable$, anotherObservable$)`

**Comment by timdeschryver** [comment]
Hi Daniel, thanks for opening this issue.
Feel free to provide a fix for this if you want.

My memory is failing me but it seems like we [explicitly check on the argument's length](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/fefd2c99cf8f374d8abd856a76ae0c3485be1eb3/src/rules/effects/prefer-concat-latest-from.ts#L92), but I can't remember why at the moment - I can take a closer look later.

You could also enable the strictness of this rule [docs](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/docs/rules/prefer-concat-latest-from.md#rule-config) this should detect it as an error.

**Comment by NiklasPor** [comment]
Thanks a lot for the quick fix @timdeschryver ❤️  And also thanks a lot for maintaining this great package 👍

**Comment by timdeschryver** [comment]
@NiklasPor 🤗
