### ISSUE TITLE
Bug avoid-mapping-selectors triggered after a switchMap

### ISSUE THREAD

**Issue by potray** [timdeschryver/eslint-plugin-ngrx#282]
## Behavior

Doing a map after a switchMap triggers `avoid-mapping-selectors`.

## Code snippet
```typescript
@Injectable({
  providedIn: 'root'
})
export class CollectionService {

  constructor(
    private service: Service,
    private store: Store
  ) {
  }

  getEntities$(): Observable<Entity[]> {
    return this.store.select(selectUser).pipe(
      switchMap(user => this.service.getCollection(user)),
      map(transformCollection),
    );
  }
}
```

## I would be willing to submit a PR to fix this issue :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
Is there a reason why this isn't written as an effect?

**Comment by timdeschryver** [comment]
Hi, thanks for creating the issue.
I suggest to use the `map` operator on the inner observable, and to also include a `catchError`.
See #283 for an example.

**Comment by potray** [comment]
I see! That works like a charm, thanks! 

I'm trying to improve my skills with ngrx and rxjs. Is there a best practice I'm not following in my code?
