### ISSUE TITLE
Performance regression when using the recommended preset in an nx workspace

### ISSUE THREAD

**Issue by mattlewis92** [timdeschryver/eslint-plugin-ngrx#284]
## Behavior

When upgrading to the latest version of this plugin we noticed our CI started running out of memory when linting. Eventually we managed to track it down to this PR: https://github.com/timdeschryver/eslint-plugin-ngrx/pull/264 Because the `tsconfigRootDir` option is not set, the linting is using the root tsconfig file from our nx workspace which includes all files in the workspace. So because we have ~300 nx libraries it means 300 typescript programs get created which include every file in the workspace instead of just the individual libraries files and our CI runs out of memory / takes an extremely long time to complete.

I'm not really sure what the optimal solution is here, given that `tsconfigRootDir` has to be set inside each libraries eslint config perhaps it should just be left up to the user to enable parserServices? Or perhaps a second set of presets could be created which don't include typechecking rules?

## Code snippet

N/A, just use the `plugin:ngrx/recommended` preset.

## I would be willing to submit a PR to fix this issue :heart:

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
For now, you could disable `ngrx/no-multiple-actions-in-effects` and/or `ngrx/avoid-cyclic-effects` which could resolve the issue for now, until we've found the root cause.

**Comment by timdeschryver** [comment]
Maybe that this could also help to find the culprit 🤔
https://duncanleung.com/profile-measure-find-remove-slow-eslint-rules/

**Comment by mattlewis92** [comment]
Thanks @timdeschryver! This looks like a pretty decent solution

**Comment by timdeschryver** [comment]
Great to hear that @mattlewis92 - thanks again for raising this issue
