### ISSUE TITLE
Bug avoid-mapping-selectors error but using 'this' in the mapping so I can't create a selector

### ISSUE THREAD

**Issue by Yohandah** [timdeschryver/eslint-plugin-ngrx#285]
## Behavior

I have the following snippet in a Guard :

```
return this.store.select(selectIsAuthenticated).pipe(
    take(1),
    map((isAuthenticated: boolean) => (isAuthenticated ? true : this.router.parseUrl('/login'))),
)
```

I want to return a UrlTree if I'm not authenticated, but the follwing error is firing 
`Map logic at the selector level instead.(ngrx/avoid-mapping-selectors)`

The problem is that in a selector I can't use dependency injection, so I can't map at the selector level. Maybe the rule should be disabled if `this` is used in the context of the mapping ?

## I would be willing to submit a PR to fix this issue :heart:
I can try but not sure I'll succeed
[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
@Yohandah that's actually something that I haven't thought of, thanks for raising this issue!
The proposed fix seems lik a good one to me, we could perhaps later enhance this further by checking where the selector is invoked (if that's possible).

Feel free to try to implement a fix if you want.
If you're stuck and/or need some help, feel free to let me know.
