### ISSUE TITLE
Keeping the recommended config up to date

### ISSUE THREAD

**Issue by timdeschryver** [timdeschryver/eslint-plugin-ngrx#32]
I think we forgot to add some of the newer rules to the [recommended config](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/master/src/configs/recommended.json). 

I wonder if we could keep them up to date by looking at the `recommended` property of each rule.  I think we could add a test that verifies if all rules are included in the recommended config (enabled and disabled).

The test would look similar to https://github.com/timdeschryver/eslint-plugin-ngrx/blob/master/tests/exported-rules.test.ts but for the config.

Thoughts @jsaguet ?

**Comment by jsaguet** [comment]
Indeed, no-multiple-actions-in-effects is missing, my bad.
I can have a look at the test, it can be useful combined with the exported-rules

**Comment by jsaguet** [comment]
#33 😃
