### ISSUE TITLE
Add ng-add command

### ISSUE THREAD

**Issue by timdeschryver** [timdeschryver/eslint-plugin-ngrx#36]
- adds `eslint-plugin-ngrx` to package.json
- configures eslint with the recommended config (or we ask which rules to enable, like we did in [ngrx-tslint-rules](https://github.com/timdeschryver/ngrx-tslint-rules/blob/master/src/schematics/ng-add/index.ts))

**Comment by jsaguet** [comment]
I'd like to try this one out.

I was thinking also checking if there is a tslint configuration still present in the projet and migrate ngrx-tslint-rules accordingly.

**Comment by timdeschryver** [comment]
Thanks for willing to pick this up @jsaguet , feel free to ping me whenever.
I think we should focus this issue to adding the command, the migration can be done later.

**Comment by jsaguet** [comment]
I didn't have time to work on this and I won't have time in the next weeks either so you can take this if you want to. No need to wait for me

**Comment by timdeschryver** [comment]
No problem 🙂
