### ISSUE TITLE
ngrx-avoid-dispatching-multiple-actions-sequentially not triggering when the field variable is named store$ instead of store

### ISSUE THREAD

**Issue by hanna-becker** [timdeschryver/eslint-plugin-ngrx#44]
Hi, thank you for providing this linter extension, I find it really useful for keeping our code base clean and maintainable. Just noticed that after also adding the "rxjs-tslint-rules" package to enforce Finnish notation on observables, the "ngrx-avoid-dispatching-multiple-actions-sequentially" rule seems not to be detecting issues like this one anymore:

this.store$.dispatch(chooseSong({song: this.song}));
this.store$.dispatch(play({positionMs}));

When I rename it to remove the $, the warning is issued as expected.

**Comment by timdeschryver** [comment]
@hanna-becker this [commit](https://github.com/timdeschryver/ngrx-tslint-rules/commit/36e095b9aa16a5e7fa72eee5740e220a4b9e9cb0) in the ngrx tslint repostory should fix this issue, which is available in v2.1.3. It's a quickfix, a more robus fix is provided in the eslint package.

**Comment by hanna-becker** [comment]
Yeah, it's working now. Awesome, thank you so much!

**Comment by timdeschryver** [comment]
I've noticed more rules depending on `store`.
I'll try to rewrite them all in the eslint package.
Perhaps later, also in the tslint rules package.
