### ISSUE TITLE
avoid-dispatching-multiple-actions-sequentially rule throws error on node without expression object

### ISSUE THREAD

**Issue by patoncrispy** [timdeschryver/eslint-plugin-ngrx#47]
https://github.com/timdeschryver/eslint-plugin-ngrx/pull/45 introduced an issue with the `avoid-dispatching-multiple-actions-sequentially` rule. 

This is the stack trace:

```
TypeError: Cannot read property 'type' of undefined
Occurred while linting /Users/me/code/project/path/to/file/component.ts:98
    at Object.isCallExpression (/Users/me/code/project/node_modules/eslint-plugin-ngrx/utils/helper-functions/guards.js:14:17)
    at /Users/me/code/project/node_modules/eslint-plugin-ngrx/rules/avoid-dispatching-multiple-actions-sequentially.js:36:33
    at Array.map (<anonymous>)
    at _a.ClassDeclaration > ClassBody > MethodDefinition > FunctionExpression > BlockStatement (/Users/me/code/project/node_modules/eslint-plugin-ngrx/rules/avoid-dispatching-multiple-actions-sequentially.js:35:22)
    at /Users/me/code/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/me/code/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/me/code/project/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/me/code/project/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/me/code/project/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
```

The code it's tripping up on is this: 
```
  linkClicked(): void {
    if (this.mediaObserver.isActive('xs') || this.mediaObserver.isActive('sm')) {
      this.store.dispatch(closeSidenav());
    }
  }
```

If I revert to 1.9.0 this problem goes away.

Simply null-checking `expression.expression` (https://github.com/timdeschryver/eslint-plugin-ngrx/blob/master/src/rules/avoid-dispatching-multiple-actions-sequentially.ts#L48) stops the exception from occuring, but I'm not sure it's the best solution.

**Comment by timdeschryver** [comment]
Thanks for filing this issue!
It seems like you've taken a look into it already, do you want to create a PR for this?

The steps would be to add your snippet to the [tests](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/master/tests/rules/avoid-dispatching-multiple-actions-sequentially.test.ts#L9) and make sure that they pass 😁

**Comment by patoncrispy** [comment]
Hey @timdeschryver, yeah would be happy to do that. 👍 I'll try get one done tomorrow!

**Comment by patoncrispy** [comment]
I'm not familiar with how eslint plugins work (at a lower level) so is there some documentation you recommend I read before getting started?

**Comment by timdeschryver** [comment]
The docs are a bit lacking for for typescript eslint.
Sadly, we don't have docs. There's another [contributing file](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/CONTRIBUTING.md) that you can read for now. The setup is identical in our repositories. 

To get started you will have to

- fork this repo
- clone your repo locally
- run `npm ci`
- run `npm test`, everything should work for now
- add the test case
- run `npm test` again, and now it should fail
- you can modify the [source code of the rule](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/master/src/rules/avoid-dispatching-multiple-actions-sequentially.ts#L18) until the test passes.

I hope this helps you. If that's not the case, feel free to ask any questions or ask if someone else picks up this issue. 
Take your time, there's no rush.

For me, I'll try to get some docs up this week.

**Comment by patoncrispy** [comment]
Nah that's perfect. Thanks!

**Comment by timdeschryver** [comment]
@patoncrispy did you had to do something else that wasn't in the list above?
I'm asking since I'm going to use it as a baseline to create the contributing docs.

**Comment by patoncrispy** [comment]
No, that was actually pretty on the money. I did have to update my fork, so it might be worth including a bit on that, maybe? The GitHub docs on updating forks are pretty good though.

**Comment by patoncrispy** [comment]
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
