### ISSUE TITLE
Enforce the use of interface for lifecycles

### ISSUE THREAD

**Issue by rafaelss95** [timdeschryver/eslint-plugin-ngrx#55]
Similar to what we have in [**`codelyzer#useLifecycleInterface`**]( https://github.com/mgechev/codelyzer/blob/5bfc15cacd688fb9057a4ed357d8a0814bb53be6/src/useLifecycleInterfaceRule.ts), I want to suggest the creation of a rule to enforce the use of interface when using the [**`NgRx effects lifecycle`**](https://github.com/ngrx/platform/blob/e8fe9fdc6f8603de949f8dc50701fe21a762f13f/modules/effects/src/lifecycle_hooks.ts).

**Comment by timdeschryver** [comment]
Do you want to create a PR for this @rafaelss95 ?

**Comment by timdeschryver** [comment]
I'm working on this.

**Comment by timdeschryver** [comment]
@all-contributors please add @rafaelss95  for ideas
