### ISSUE TITLE
New rule: prefer-ngrxPush over async pipe

### ISSUE THREAD

**Issue by dev054** [timdeschryver/eslint-plugin-ngrx#58]
Hey @timdeschryver great lib, btw! I wonder if we could have a rule that enforces the preference of `ngrxPush` instead of `async`... I don't know if it's in the scope of the project as I didn't see any template rule (and in fact I have much low knowledge about this world in general).

**Comment by timdeschryver** [comment]
Hi @dev054 , the push pipe is experimental, so I'm hesitant to add this rule.

**Comment by jkremlacek** [comment]
Unless I am mistaken, push pipe is no longer experimental. Would it make sense to reconsider this rule request @timdeschryver ? This rule would be really helpful.

**Comment by timdeschryver** [comment]
Feel free to pick this up @jkremlacek .
If we do this, we should also add a ngrx/component config for ESLint, otherwise it wouldn't make sense imho (and could feel like "advertising" to use ngrx/component).
Also keep in mind that this package is migrated into https://github.com/ngrx/platform
