### ISSUE TITLE
[action-hygiene] reports any call expression that starts with createAction

### ISSUE THREAD

**Issue by rafaelss95** [timdeschryver/eslint-plugin-ngrx#63]
Examples:

```ts
createActionType('123')
createActionable('123')
```

This can be easily fixed [here](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/48afe768e45da866681d59df0fe8229aeb7ddf5e/src/utils/selectors/index.ts#L5):

```diff
- export const actionCreator = `CallExpression[callee.name=/createAction.*/]`
+ export const actionCreator = `CallExpression[callee.name='createAction']`
```

<hr>

@timdeschryver if you agree I can submit a PR for this.

**Comment by timdeschryver** [comment]
Feel free to change this @rafaelss95 , thanks!
The reasoning behind this was a custom `createAction` implementation, but it doesn't make sense to add this here 😅
