### ISSUE TITLE
New rule: action prop name

### ISSUE THREAD

**Issue by timdeschryver** [timdeschryver/eslint-plugin-ngrx#66]
Ref: https://github.com/ngrx/platform/issues/2892

**Comment by rafaelss95** [comment]
Hey Tim, could you clarify what expectations of success and fail with this rule? I'm interested on working on this if possible.

**Comment by timdeschryver** [comment]
I prefer inline types in props instead of using interfaces, e.g.

```diff
- const foo = createAction('foo', props<Person>());
+ const foo = createAction('foo', props<{id: number, name: string}>());
```
