### ISSUE TITLE
[avoid-combining-selectors] Unexpected behaviors

### ISSUE THREAD

**Issue by rafaelss95** [timdeschryver/eslint-plugin-ngrx#75]
Similar to #74,

1. It doesn't report when we use something other than `store`:

`readonly something$ = combineLatest(this.store$.select(AuthSelectors.selectUser), this.store$.select(AuthSelectors.something))`

2. It doesn't report when we use `store.pipe` instead of `store.select`:

`readonly something$ = combineLatest(this.store$.pipe(select(AuthSelectors.selectUser)), this.store$.select(AuthSelectors.something))`

**Comment by timdeschryver** [comment]
Do you know if we find the store name at runtime?
If not, we can look for `store` and `store$` this will cover most of the cases by default.

Having a parameter for the rule also works, but then every rule needs to be configured.
IIRC there's also a global config that we can use where the user can provide a store name. (we can also create a new rule based on this to keep the store's name consistent)

**Comment by timdeschryver** [comment]
Fyi, I didn't add this because we recommend `store.select`. 
But I agree that the other case should also be covered 😅

**Comment by rafaelss95** [comment]
> we can also create a new rule based on this to keep the store's name consistent)

Yes, please 🙏 

> EDIT: here's a link to the shared config https://eslint.org/docs/user-guide/configuring/configuration-files#adding-shared-settings

This option is really nice, I didn't know it until now 😄

> Fyi, I didn't add this because we recommend `store.select`.
> But I agree that the other case should also be covered 😅

Aha, that's fine. After the merge of #80 I can send a PR that cover this :)
