### ISSUE TITLE
Create a config that exposes all the rules in the package

### ISSUE THREAD

**Issue by rafaelss95** [timdeschryver/eslint-plugin-ngrx#77]
Similar to what we have in [**angular-eslint**](https://github.com/angular-eslint/angular-eslint/blob/ea133b4f5302385e6e6971f027a164e025ad1472/packages/eslint-plugin/src/configs/all.json), I'd like to propose the creation of the config that exposes all the rules in this package.

**Comment by timdeschryver** [comment]
Looks good to me 👍
