### ISSUE TITLE
Document rules  fixes/suggestions

### ISSUE THREAD

**Issue by rafaelss95** [timdeschryver/eslint-plugin-ngrx#78]
I'm creating this so that we don't forget to document what we discussed at https://github.com/timdeschryver/eslint-plugin-ngrx/pull/67 :)

As a suggestion it could be something like [**this**](https://github.com/cartant/eslint-plugin-rxjs#rules).

**Comment by timdeschryver** [comment]
This is included while we [generate the readme](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/master/scripts/generate-readme.ts).
