### ISSUE TITLE
Use guards from eslint-etc

### ISSUE THREAD

**Issue by rafaelss95** [timdeschryver/eslint-plugin-ngrx#81]
I'm creating this issue to make sure we don't forget the discussion on https://github.com/timdeschryver/eslint-plugin-ngrx/pull/72#discussion_r572065340

**Comment by timdeschryver** [comment]
Let's refactor this with the implementation of @MichaelDeBoey.
We can take inspiration from the eslint plugin of testing-library (https://github.com/testing-library/eslint-plugin-testing-library/pull/329)

**Comment by MichaelDeBoey** [comment]
PR is created: https://github.com/timdeschryver/eslint-plugin-ngrx/pull/106
