### ISSUE TITLE
[avoid-combining-selectors] derived state from multiple feature states

### ISSUE THREAD

**Issue by rainerhahnekamp** [timdeschryver/eslint-plugin-ngrx#97]
Hi, I have a question about the "Avoid Combining Selectors" rule.

Suppose you two have modules with their own feature states. The interfaces of these modules are implemented following the facade pattern and expose parts of their state as Observables. Module A has a dependency to Module B's exposed state.

It would not be possible to use the observables of my facade in module's A selectors, because the selectors don't support injection of services.

As an alternative, I would construct the ViewModel in a container component of module A. combineLatest would use facade of module B and a selector of the internal state. That looks reasonable to me but violates the linting rule. What to do here?

Thanks!

**Comment by timdeschryver** [comment]
Hi, that's a good question.  

As I don't use facades I don't run into this problem 😅.
I think disabling this rule would be the way to go, as I don't see a workaround for this and this structure is valid for facades.

If we notice that more rules need to be disabled to be able to work with facades, we could introduce a "facade config".

**Comment by rainerhahnekamp** [comment]
Hi, thanks for your quick answer.
I guess the generic term would be a module's API. Facade is just one possible design pattern. Either way, thanks Tim!
